export const siteConfig = {
	name: "portfolio",
	url: "https://portfolio.colidevs.com",
	ogImage: "https://portfolio.colidevs.com/og.jpg",
	description: "portfolio generated by create-coliapp",
	links: {
		instagram: "https://instagram.com/colidevs",
	},
};

export type SiteConfig = typeof siteConfig;
